### ISSUE TITLE
0.9.25 breaks build on go 1.15

### ISSUE THREAD

**Issue by Xuanwo** [mautrix/go#42]
Commit https://github.com/mautrix/go/commit/1380e2387f7a08b59fa88a920587654edefa165b breaks mautrix/go build on go 1.15.

## Cause

`os.CreateTemp` is introduced in go 1.16, and will be failed to build on go 1.15 like:

```shell
 go vet ./...
# maunium.net/go/mautrix
Error: ../../../go/pkg/mod/maunium.net/go/mautrix@v0.9.25/client.go:447:15: undefined: os.CreateTemp
make: *** [Makefile:19: vet] Error 2
Error: Process completed with exit code 2.
```

Related build log: https://github.com/beyondstorage/go-community/pull/34/checks?check_run_id=3648623888

## Fix

`mautrix/go` should be able to build on `go 1.14` as described in `go.mod`:

https://github.com/mautrix/go/blob/5dd96e0cc0eace619b1ef1718806e1af691e1862/go.mod#L3

So here are some possible fixes:

- Increase build requirement from `go 1.14` to `go 1.16`.
- Use `ioutil.TempFile` instead.

To avoid those problems, maybe we can introduce GitHub actions to build upon all supported go versions?
